#!/usr/bin/python3
import pip
pip.main(['install', 'eclipse-sumo'])

import sys
from sumo import sumo
if __name__ == '__main__':
    if sys.argv[0].endswith('.exe'):
        sys.argv[0] = sys.argv[0][:-4]
    sys.exit(sumo())
